import './globals.css';
import "./whatsapp.css"
import"./banner.css"
import'./backround.css'
import Navbar from './components/Navbar/index';
import Footertwo from './components/Footertwo/index';
import Head from 'next/head';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<Head>
  <title>malkyopwielen</title>
  <meta name="description" content="Generated by create next app" />
  <link rel="icon" href="/favicon.ico" />
  <link rel="apple-touch-icon" href="/favicon/apple-touch-icon.png" />
  <link rel="manifest" href="/favicon/site.webmanifest" />
</Head>

      <body>
        <Navbar />
        {children}
        <Footertwo />
      </body>
    </html>
  );
}
